---
abstract: 'OAuth 2.0 Library'
author:
  - 'Lyo Kato, <lyo.kato@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OAuth-Lite2
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0.34
  Class::ErrorHandler: 0.01
  Data::Dump: 1.17
  Digest::SHA: 5.48
  Hash::MultiValue: 0.08
  IO::String: 1.08
  JSON: 2.21
  LWP::UserAgent: 0
  Params::Validate: 0.95
  Plack: 0.09942
  Scalar::Util: 1.23
  String::Random: 0.22
  Try::Tiny: 0.06
  URI: 1.54
  XML::LibXML: 1.7
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_03
