---
abstract: 'OAuth 2.0 Library'
author:
  - 'Lyo Kato, <lyo.kato@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.920'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OAuth-Lite2
no_index:
  directory:
    - inc
    - t
requires:
  Class::ErrorHandler: 0
  Digest::SHA: 0
  Hash::MultiValue: 0
  IO::String: 0
  JSON: 0
  LWP::UserAgent: 0
  Params::Validate: 0
  Plack: 0
  Plack::Request: 0
  Scalar::Util: 0
  String::Random: 0
  Try::Tiny: 0
  URI::Escape: 0
  XML::LibXML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
